#!/usr/bin/env node

/**
 * Fetch the Hinglish VTT subtitle file for a given tpStreamId.
 *
 * Usage:
 *   node utils-scripts/fetch-vtt.js <tpStreamId>
 *   node utils-scripts/fetch-vtt.js <tpStreamId> --output=path/to/save.vtt
 *
 * Examples:
 *   node utils-scripts/fetch-vtt.js GffkmXKJ58m
 *   node utils-scripts/fetch-vtt.js 7NPTbp7SU5J --output=input.vtt
 */

const https = require("https");
const fs = require("fs");
const path = require("path");

const CLOUDFRONT_BASE = "https://d44tj0kek3n57.cloudfront.net/transcoded";
const OUTPUT_DIR = path.join(__dirname, "../output");

function fetchVTT(url) {
  return new Promise((resolve, reject) => {
    const req = https.get(url, (res) => {
      if (res.statusCode === 404 || res.statusCode === 403) {
        res.resume();
        return resolve(null);
      }
      if (res.statusCode !== 200) {
        res.resume();
        return reject(new Error(`HTTP ${res.statusCode}`));
      }
      const chunks = [];
      res.on("data", (c) => chunks.push(c));
      res.on("end", () => resolve(Buffer.concat(chunks).toString("utf-8")));
    });
    req.on("error", reject);
    req.setTimeout(30000, () => { req.destroy(); reject(new Error("Timeout")); });
  });
}

async function main() {
  const args = process.argv.slice(2);
  const flags = {};
  let tpStreamId = null;

  for (const arg of args) {
    if (arg.startsWith("--")) {
      const [key, ...rest] = arg.slice(2).split("=");
      flags[key] = rest.join("=") || true;
    } else if (!tpStreamId) {
      tpStreamId = arg;
    }
  }

  if (!tpStreamId) {
    console.error("Usage: node utils-scripts/fetch-vtt.js <tpStreamId> [--output=path]");
    process.exit(1);
  }

  const vttUrl = `${CLOUDFRONT_BASE}/${tpStreamId}/subtitles/en-autogenerated.vtt`;
  console.log(`Fetching VTT for tpStreamId: ${tpStreamId}`);
  console.log(`URL: ${vttUrl}\n`);

  let content;
  try {
    content = await fetchVTT(vttUrl);
  } catch (err) {
    console.error(`Failed to fetch: ${err.message}`);
    process.exit(1);
  }

  if (!content || !content.includes("WEBVTT")) {
    console.error("No subtitles found for this tpStreamId.");
    process.exit(1);
  }

  const cueCount = (content.match(/-->/g) || []).length;

  let outputPath;
  if (flags.output) {
    outputPath = path.resolve(flags.output);
  } else {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
    outputPath = path.join(OUTPUT_DIR, `${tpStreamId}.vtt`);
  }

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, content, "utf-8");

  const sizeKB = (Buffer.byteLength(content, "utf-8") / 1024).toFixed(1);
  console.log(`Saved: ${outputPath}`);
  console.log(`Size:  ${sizeKB} KB`);
  console.log(`Cues:  ${cueCount}`);
}

main();
