require("dotenv").config();

// Parse --voice=male|female (default from .env SARVAM_VOICE)
const _voiceArg = process.argv.find(a => a.startsWith("--voice="));
if (_voiceArg) process.env.SARVAM_VOICE = _voiceArg.split("=")[1].toLowerCase();

const fs = require("fs");
const path = require("path");
const https = require("https");
const { execFileSync, spawn } = require("child_process");
const { processPipeline } = require("../src/pipeline");
const { fmtDuration } = require("../src/utils/format");
const L = require("../src/utils/logger");

// ── Config ───────────────────────────────────────────────────────────────────

const TP_STREAM_ID = "3SqXfnbkdGd";
const CLOUDFRONT_BASE = "https://d44tj0kek3n57.cloudfront.net/transcoded";
const OUTPUT_DIR = path.join(__dirname, "../output", TP_STREAM_ID);
const TMP_DIR = path.join(OUTPUT_DIR, "tmp");

const START_SEC = 420; // 7:00
const END_SEC = 600;   // 10:00

// ── Fetch VTT ────────────────────────────────────────────────────────────────

function fetchVTT(url) {
  return new Promise((resolve, reject) => {
    const req = https.get(url, (res) => {
      if (res.statusCode === 404 || res.statusCode === 403) {
        res.resume();
        return resolve(null);
      }
      if (res.statusCode !== 200) {
        res.resume();
        return reject(new Error(`HTTP ${res.statusCode}`));
      }
      const chunks = [];
      res.on("data", (c) => chunks.push(c));
      res.on("end", () => resolve(Buffer.concat(chunks).toString("utf-8")));
    });
    req.on("error", reject);
    req.setTimeout(30000, () => { req.destroy(); reject(new Error("Timeout")); });
  });
}

// ── Trim VTT to time range ───────────────────────────────────────────────────

function trimVTT(vttContent, startSec, endSec) {
  const lines = vttContent.replace(/\r\n/g, "\n").split("\n");
  const cues = [];
  let i = 0;
  while (i < lines.length && !lines[i].startsWith("WEBVTT")) i++;
  i++;

  while (i < lines.length) {
    if (!lines[i] || lines[i].trim() === "") { i++; continue; }
    if (lines[i].trim().startsWith("NOTE")) {
      while (i < lines.length && lines[i].trim() !== "") i++;
      continue;
    }
    const cue = { id: null, timestamp: null, text: [] };
    if (lines[i] && !lines[i].includes("-->")) { cue.id = lines[i].trim(); i++; }
    if (lines[i] && lines[i].includes("-->")) { cue.timestamp = lines[i].trim(); i++; }
    else { i++; continue; }
    while (i < lines.length && lines[i].trim() !== "") { cue.text.push(lines[i].trim()); i++; }
    if (cue.timestamp) cues.push(cue);
  }

  // Filter cues within range and shift timestamps to start from 0
  const filtered = [];
  for (const cue of cues) {
    const [sStr, eStr] = cue.timestamp.split("-->").map(s => s.trim());
    const s = timeToSec(sStr);
    const e = timeToSec(eStr);
    if (e <= startSec || s >= endSec) continue;
    const newStart = Math.max(0, s - startSec);
    const newEnd = Math.min(endSec - startSec, e - startSec);
    filtered.push({
      ...cue,
      timestamp: `${secToVtt(newStart)} --> ${secToVtt(newEnd)}`,
    });
  }

  let out = "WEBVTT\n\n";
  for (const c of filtered) {
    out += `${c.timestamp}\n${c.text.join("\n")}\n\n`;
  }
  return { vtt: out.trimEnd() + "\n", cueCount: filtered.length };
}

function timeToSec(str) {
  const parts = str.replace(",", ".").split(":");
  if (parts.length === 3) return +parts[0] * 3600 + +parts[1] * 60 + +parts[2];
  if (parts.length === 2) return +parts[0] * 60 + +parts[1];
  return +str;
}

function secToVtt(sec) {
  const h = Math.floor(sec / 3600);
  const m = Math.floor((sec % 3600) / 60);
  const s = sec % 60;
  return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}:${s.toFixed(3).padStart(6, "0")}`;
}

// ── ffmpeg runner ────────────────────────────────────────────────────────────

function runFfmpeg(args) {
  return new Promise((resolve, reject) => {
    const proc = spawn("ffmpeg", args, { stdio: "inherit" });
    proc.on("close", (code) => {
      if (code === 0) resolve();
      else reject(new Error(`ffmpeg exited with code ${code}`));
    });
    proc.on("error", (err) => reject(new Error(`Failed to start ffmpeg: ${err.message}`)));
  });
}

// ── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const runStart = Date.now();

  if (!process.env.OPENAI_API_KEY) {
    L.error("OPENAI_API_KEY missing in .env");
    process.exit(1);
  }

  L.banner(`QUICK RUN — 1 min clip (${START_SEC}s–${END_SEC}s) with dubbed audio`);
  L.kv("tpStream ID:", TP_STREAM_ID);
  L.kv("Time range:", `${START_SEC}s → ${END_SEC}s  (${END_SEC - START_SEC}s)`);
  L.divider();

  // Step 1 — Fetch & trim VTT
  const vttUrl = `${CLOUDFRONT_BASE}/${TP_STREAM_ID}/subtitles/en-autogenerated.vtt`;
  L.step("  Step 1/3  Fetching & trimming English VTT...");
  L.detail(`URL: ${vttUrl}`);

  const vttContent = await fetchVTT(vttUrl);
  if (!vttContent || !vttContent.includes("WEBVTT")) {
    L.error("No subtitles found for this tpStreamId.");
    process.exit(1);
  }

  const { vtt: trimmedVTT, cueCount } = trimVTT(vttContent, START_SEC, END_SEC);
  L.success(`VTT trimmed to ${cueCount} cues (${START_SEC}s–${END_SEC}s)`);

  // Save files
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  fs.mkdirSync(TMP_DIR, { recursive: true });

  const inputVTT = path.join(OUTPUT_DIR, "input_clip.vtt");
  const outputVTT = path.join(OUTPUT_DIR, "english_clip.vtt");
  const outputAudio = path.join(OUTPUT_DIR, "english_clip.wav");
  const outputVideo = path.join(OUTPUT_DIR, "preview_7m_10m.mp4");

  fs.writeFileSync(inputVTT, trimmedVTT, "utf-8");
  L.success(`Saved trimmed VTT → ${inputVTT}`);

  // Step 2 — Run pipeline
  L.divider();
  L.step("  Step 2/3  Running TTS pipeline (Phase 1 = TTS+rewrite, Phase 2 = combine)...");

  const pipelineResult = await processPipeline(inputVTT, outputVTT, outputAudio, TMP_DIR);

  // Step 3 — Download video clip & merge with dubbed audio
  L.divider();
  L.step("  Step 3/3  Merging video (6:00–7:00) with dubbed audio...");

  const videoUrl = `${CLOUDFRONT_BASE}/${TP_STREAM_ID}/720p_h264/video.m3u8`;
  L.detail(`Video: ${videoUrl}`);

  await runFfmpeg([
    "-ss", String(START_SEC),
    "-i", videoUrl,
    "-i", outputAudio,
    "-t", String(END_SEC - START_SEC),
    "-map", "0:v:0",
    "-map", "1:a:0",
    "-c:v", "copy",
    "-c:a", "aac",
    "-b:a", "192k",
    "-shortest",
    "-y",
    outputVideo,
  ]);

  L.success(`Video created → ${outputVideo}`);

  // Cleanup tmp
  if (fs.existsSync(TMP_DIR)) {
    fs.rmSync(TMP_DIR, { recursive: true, force: true });
  }

  // Summary
  const totalMs = Date.now() - runStart;
  const videoSize = (fs.statSync(outputVideo).size / 1024 / 1024).toFixed(2);
  L.banner("DONE");
  L.kv("Output video:", `${outputVideo}  [${videoSize} MB]`);
  L.kv("Output audio:", outputAudio);
  L.kv("Output VTT:", outputVTT);
  L.thinDivider();
  L.kv("Accuracy:", `${pipelineResult.accuracy}%`);
  L.kv("Audio duration:", `${pipelineResult.totalDuration.toFixed(2)}s  (expected ${pipelineResult.expectedTotal.toFixed(2)}s)`);
  L.kv("► TOTAL TIME:", fmtDuration(totalMs));
  L.divider();
  console.log(`\nOpen it with: open "${outputVideo}"`);
}

main().catch((err) => {
  L.error(`Fatal: ${err.message}`);
  console.error(err);
  process.exit(1);
});
